// Code generated by protoc-gen-go.
// source: PayProto.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	PayProto.proto

It has these top-level messages:
	Order
	OrderReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	ZoneID      string `protobuf:"bytes,1,opt,name=ZoneID,json=zoneID" json:"ZoneID,omitempty"`
	UUID        string `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	UserName    string `protobuf:"bytes,3,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	ProductID   string `protobuf:"bytes,4,opt,name=ProductID,json=productID" json:"ProductID,omitempty"`
	Amount      string `protobuf:"bytes,5,opt,name=Amount,json=amount" json:"Amount,omitempty"`
	Extra       string `protobuf:"bytes,6,opt,name=Extra,json=extra" json:"Extra,omitempty"`
	GameID      string `protobuf:"bytes,7,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	Channel     string `protobuf:"bytes,8,opt,name=Channel,json=channel" json:"Channel,omitempty"`
	DeviceType  string `protobuf:"bytes,9,opt,name=DeviceType,json=deviceType" json:"DeviceType,omitempty"`
	IMEI        string `protobuf:"bytes,10,opt,name=IMEI,json=iMEI" json:"IMEI,omitempty"`
	MAC         string `protobuf:"bytes,11,opt,name=MAC,json=mAC" json:"MAC,omitempty"`
	IPv4        string `protobuf:"bytes,12,opt,name=IPv4,json=iPv4" json:"IPv4,omitempty"`
	IPv6        string `protobuf:"bytes,13,opt,name=IPv6,json=iPv6" json:"IPv6,omitempty"`
	OS          string `protobuf:"bytes,14,opt,name=OS,json=oS" json:"OS,omitempty"`
	MODE        string `protobuf:"bytes,15,opt,name=MODE,json=mODE" json:"MODE,omitempty"`
	ProductName string `protobuf:"bytes,16,opt,name=ProductName,json=productName" json:"ProductName,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto1.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OrderReply struct {
	OrderID    string `protobuf:"bytes,1,opt,name=OrderID,json=orderID" json:"OrderID,omitempty"`
	Timestamp  string `protobuf:"bytes,2,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Sign       string `protobuf:"bytes,3,opt,name=Sign,json=sign" json:"Sign,omitempty"`
	PreOrderID string `protobuf:"bytes,4,opt,name=PreOrderID,json=preOrderID" json:"PreOrderID,omitempty"`
	Random     string `protobuf:"bytes,5,opt,name=Random,json=random" json:"Random,omitempty"`
}

func (m *OrderReply) Reset()                    { *m = OrderReply{} }
func (m *OrderReply) String() string            { return proto1.CompactTextString(m) }
func (*OrderReply) ProtoMessage()               {}
func (*OrderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*Order)(nil), "proto.Order")
	proto1.RegisterType((*OrderReply)(nil), "proto.OrderReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Pay service

type PayClient interface {
	// 创建订单
	BuildOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderReply, error)
}

type payClient struct {
	cc *grpc.ClientConn
}

func NewPayClient(cc *grpc.ClientConn) PayClient {
	return &payClient{cc}
}

func (c *payClient) BuildOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderReply, error) {
	out := new(OrderReply)
	err := grpc.Invoke(ctx, "/proto.Pay/BuildOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pay service

type PayServer interface {
	// 创建订单
	BuildOrder(context.Context, *Order) (*OrderReply, error)
}

func RegisterPayServer(s *grpc.Server, srv PayServer) {
	s.RegisterService(&_Pay_serviceDesc, srv)
}

func _Pay_BuildOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).BuildOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Pay/BuildOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).BuildOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pay",
	HandlerType: (*PayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildOrder",
			Handler:    _Pay_BuildOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x92, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0x85, 0xbe, 0xe8, 0x80, 0x88, 0x1b, 0x63, 0x36, 0xc4, 0x18, 0xc2, 0xc9, 0x13, 0x26,
	0x6a, 0xb8, 0xf3, 0x8a, 0xe1, 0x80, 0x34, 0x3c, 0x2e, 0xde, 0x6a, 0xbb, 0xc1, 0x46, 0xb6, 0xdb,
	0x94, 0x96, 0x88, 0x37, 0xff, 0x03, 0xff, 0x64, 0x77, 0x67, 0xdb, 0xea, 0x05, 0xe6, 0xfb, 0xcd,
	0xc7, 0x0e, 0x3b, 0xdf, 0x42, 0xdb, 0xf3, 0x4f, 0x5e, 0x2a, 0x32, 0x31, 0x48, 0xd4, 0x27, 0xb1,
	0xf0, 0xab, 0xff, 0x6d, 0x80, 0xb5, 0x4c, 0x43, 0x96, 0x92, 0x6b, 0xb0, 0x5f, 0x45, 0xcc, 0xe6,
	0x53, 0x5a, 0xeb, 0xd5, 0xee, 0xdc, 0x95, 0xfd, 0x85, 0x8a, 0x10, 0x30, 0xb7, 0x5b, 0x49, 0xeb,
	0x48, 0xcd, 0x5c, 0xd6, 0xa4, 0x0b, 0x8d, 0xed, 0x81, 0xa5, 0x2f, 0x3e, 0x67, 0xd4, 0x40, 0xde,
	0xc8, 0x0b, 0x4d, 0x6e, 0xc0, 0x95, 0x73, 0xc2, 0x3c, 0xc8, 0xe4, 0x8f, 0x4c, 0x6c, 0xba, 0x49,
	0x09, 0xd4, 0x94, 0x11, 0x17, 0x79, 0x9c, 0x51, 0x4b, 0x4f, 0xf1, 0x51, 0x91, 0x2b, 0xb0, 0x66,
	0x9f, 0x59, 0xea, 0x53, 0x1b, 0xb1, 0xc5, 0x94, 0x50, 0xee, 0x67, 0x79, 0xa6, 0x3c, 0xc8, 0xd1,
	0xee, 0x1d, 0x2a, 0x42, 0xc1, 0x99, 0xbc, 0xfb, 0x71, 0xcc, 0xf6, 0xb4, 0x81, 0x0d, 0x27, 0xd0,
	0x92, 0xdc, 0x02, 0x4c, 0xd9, 0x31, 0x0a, 0xd8, 0xe6, 0x94, 0x30, 0xea, 0x62, 0x13, 0xc2, 0x8a,
	0xa8, 0xdb, 0xcc, 0x17, 0xb3, 0x39, 0x05, 0x7d, 0x9b, 0x48, 0xd6, 0xa4, 0x03, 0xc6, 0x62, 0x34,
	0xa1, 0x4d, 0x44, 0x06, 0x1f, 0x4d, 0xd0, 0xe5, 0x1d, 0x9f, 0x68, 0xab, 0x70, 0xc9, 0xba, 0x60,
	0x43, 0x7a, 0x5e, 0xb1, 0x21, 0x69, 0x43, 0x7d, 0xb9, 0xa6, 0x6d, 0x24, 0x75, 0xb1, 0x56, 0x9e,
	0xc5, 0x72, 0x3a, 0xa3, 0x17, 0xda, 0xc3, 0x65, 0x4d, 0x7a, 0xd0, 0x2c, 0xf6, 0x81, 0xeb, 0xea,
	0x60, 0xab, 0x99, 0xfc, 0xa1, 0xfe, 0x4f, 0x0d, 0x00, 0x33, 0x58, 0xb1, 0x64, 0x7f, 0x52, 0x97,
	0x43, 0x55, 0x25, 0xe1, 0x08, 0x2d, 0xd5, 0x6a, 0x37, 0x11, 0x67, 0x87, 0xcc, 0xe7, 0x49, 0x91,
	0x87, 0x9b, 0x95, 0x40, 0x0d, 0x5f, 0x47, 0xbb, 0xb8, 0x08, 0xc4, 0x3c, 0xc8, 0x5a, 0xad, 0xc3,
	0x4b, 0x59, 0x79, 0x9c, 0x4e, 0x03, 0x92, 0x8a, 0xa8, 0x05, 0xaf, 0xfc, 0x38, 0x14, 0xbc, 0x8c,
	0x23, 0x45, 0xf5, 0x30, 0x04, 0x43, 0xbe, 0x17, 0x72, 0x0f, 0x30, 0xce, 0xa3, 0x7d, 0xa8, 0x5f,
	0x48, 0x4b, 0x3f, 0x9d, 0x01, 0xaa, 0xee, 0xe5, 0x7f, 0x85, 0xff, 0xbc, 0x7f, 0x36, 0x6e, 0x01,
	0x04, 0x82, 0x0f, 0xe2, 0x0f, 0x15, 0xd4, 0x9b, 0x8d, 0x8e, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x49, 0x49, 0x6e, 0x4e, 0x7c, 0x02, 0x00, 0x00,
}
