// Code generated by protoc-gen-go.
// source: LogProto.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	LogProto.proto

It has these top-level messages:
	NiKLogger
	R
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NiKLogger struct {
	LogType    string `protobuf:"bytes,1,opt,name=LogType,json=logType" json:"LogType,omitempty"`
	LogContent string `protobuf:"bytes,2,opt,name=LogContent,json=logContent" json:"LogContent,omitempty"`
}

func (m *NiKLogger) Reset()                    { *m = NiKLogger{} }
func (m *NiKLogger) String() string            { return proto1.CompactTextString(m) }
func (*NiKLogger) ProtoMessage()               {}
func (*NiKLogger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type R struct {
}

func (m *R) Reset()                    { *m = R{} }
func (m *R) String() string            { return proto1.CompactTextString(m) }
func (*R) ProtoMessage()               {}
func (*R) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*NiKLogger)(nil), "proto.NiKLogger")
	proto1.RegisterType((*R)(nil), "proto.R")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for NiKLog service

type NiKLogClient interface {
	// 日志通用传送接口
	SendLog(ctx context.Context, in *NiKLogger, opts ...grpc.CallOption) (*R, error)
}

type niKLogClient struct {
	cc *grpc.ClientConn
}

func NewNiKLogClient(cc *grpc.ClientConn) NiKLogClient {
	return &niKLogClient{cc}
}

func (c *niKLogClient) SendLog(ctx context.Context, in *NiKLogger, opts ...grpc.CallOption) (*R, error) {
	out := new(R)
	err := grpc.Invoke(ctx, "/proto.NiKLog/SendLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NiKLog service

type NiKLogServer interface {
	// 日志通用传送接口
	SendLog(context.Context, *NiKLogger) (*R, error)
}

func RegisterNiKLogServer(s *grpc.Server, srv NiKLogServer) {
	s.RegisterService(&_NiKLog_serviceDesc, srv)
}

func _NiKLog_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NiKLogger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NiKLogServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NiKLog/SendLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NiKLogServer).SendLog(ctx, req.(*NiKLogger))
	}
	return interceptor(ctx, in, info, handler)
}

var _NiKLog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NiKLog",
	HandlerType: (*NiKLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _NiKLog_SendLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0xc9, 0x4f, 0x0f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0xac, 0x60, 0x4a, 0xc9, 0x95, 0x8b, 0xd3,
	0x2f, 0xd3, 0x1b, 0x28, 0x97, 0x9e, 0x5a, 0x24, 0x24, 0xc1, 0xc5, 0x0e, 0x64, 0x85, 0x54, 0x16,
	0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0xe7, 0x40, 0xb8, 0x42, 0x72, 0x5c, 0x5c,
	0x40, 0x19, 0xe7, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0xb0, 0x24, 0x57, 0x0e, 0x5c,
	0x44, 0x89, 0x99, 0x8b, 0x31, 0xc8, 0xc8, 0x90, 0x8b, 0x0d, 0x62, 0x96, 0x90, 0x3a, 0x17, 0x7b,
	0x70, 0x6a, 0x5e, 0x0a, 0x88, 0x29, 0x00, 0xb1, 0x4f, 0x0f, 0x6e, 0x8b, 0x14, 0x07, 0x54, 0x24,
	0x48, 0x89, 0x21, 0x89, 0x0d, 0xcc, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0xd2, 0x63,
	0x5a, 0x9e, 0x00, 0x00, 0x00,
}
