// Code generated by protoc-gen-go.
// source: token.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	token.proto

It has these top-level messages:
	TokenRequest
	TokenReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenRequest struct {
	UUID string `protobuf:"bytes,1,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto1.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TokenReply struct {
	Token string `protobuf:"bytes,1,opt,name=Token,json=token" json:"Token,omitempty"`
}

func (m *TokenReply) Reset()                    { *m = TokenReply{} }
func (m *TokenReply) String() string            { return proto1.CompactTextString(m) }
func (*TokenReply) ProtoMessage()               {}
func (*TokenReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*TokenRequest)(nil), "proto.TokenRequest")
	proto1.RegisterType((*TokenReply)(nil), "proto.TokenReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Token service

type TokenClient interface {
	GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error)
}

type tokenClient struct {
	cc *grpc.ClientConn
}

func NewTokenClient(cc *grpc.ClientConn) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	out := new(TokenReply)
	err := grpc.Invoke(ctx, "/proto.Token/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Token service

type TokenServer interface {
	GetToken(context.Context, *TokenRequest) (*TokenReply, error)
}

func RegisterTokenServer(s *grpc.Server, srv TokenServer) {
	s.RegisterService(&_Token_serviceDesc, srv)
}

func _Token_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Token/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).GetToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Token_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _Token_GetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xcf, 0x4e,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4a, 0x5c, 0x3c, 0x21,
	0x20, 0xd1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xd0, 0x50, 0x4f,
	0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x96, 0x52, 0x20, 0x1b, 0xa8, 0x86, 0x0b, 0xaa,
	0xa6, 0x20, 0xa7, 0x52, 0x48, 0x84, 0x8b, 0x15, 0xcc, 0x83, 0x2a, 0x61, 0x05, 0x1b, 0x6a, 0x64,
	0x0b, 0x15, 0x15, 0x32, 0xe1, 0xe2, 0x70, 0x4f, 0x2d, 0x81, 0xb0, 0x85, 0x21, 0x76, 0xe9, 0x21,
	0xdb, 0x20, 0x25, 0x88, 0x2a, 0x08, 0x34, 0x52, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x66, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x7b, 0x88, 0x69, 0x17, 0xa3, 0x00, 0x00, 0x00,
}
