// Code generated by protoc-gen-go.
// source: LoginProto.proto
// DO NOT EDIT!

/*
Package SDKProto is a generated protocol buffer package.

It is generated from these files:
	LoginProto.proto

It has these top-level messages:
	DeviceInfo
	RegisterRequest
	AccountLoginRequest
	PhoneLoginRequest
	LoginReply
	AuthCodeRequest
	Reply
	AutoLoginRequest
	BindingPhoneRequest
	BindingAccountRequest
	ChangePassWordRequest
	WeixinLoginRequest
*/
package SDKProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceInfo struct {
	GameID     string `protobuf:"bytes,1,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	Channel    string `protobuf:"bytes,2,opt,name=Channel,json=channel" json:"Channel,omitempty"`
	DeviceType string `protobuf:"bytes,3,opt,name=DeviceType,json=deviceType" json:"DeviceType,omitempty"`
	IMEI       string `protobuf:"bytes,4,opt,name=IMEI,json=iMEI" json:"IMEI,omitempty"`
	MAC        string `protobuf:"bytes,5,opt,name=MAC,json=mAC" json:"MAC,omitempty"`
	IPv4       string `protobuf:"bytes,6,opt,name=IPv4,json=iPv4" json:"IPv4,omitempty"`
	IPv6       string `protobuf:"bytes,7,opt,name=IPv6,json=iPv6" json:"IPv6,omitempty"`
	OS         string `protobuf:"bytes,8,opt,name=OS,json=oS" json:"OS,omitempty"`
	Latitude   string `protobuf:"bytes,9,opt,name=Latitude,json=latitude" json:"Latitude,omitempty"`
	Longitude  string `protobuf:"bytes,10,opt,name=Longitude,json=longitude" json:"Longitude,omitempty"`
}

func (m *DeviceInfo) Reset()                    { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()               {}
func (*DeviceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 注册普通账号
type RegisterRequest struct {
	UserName   string      `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	PassWord   string      `protobuf:"bytes,2,opt,name=PassWord,json=passWord" json:"PassWord,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 普通账号登陆
type AccountLoginRequest struct {
	UserName   string      `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	PassWord   string      `protobuf:"bytes,2,opt,name=PassWord,json=passWord" json:"PassWord,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *AccountLoginRequest) Reset()                    { *m = AccountLoginRequest{} }
func (m *AccountLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountLoginRequest) ProtoMessage()               {}
func (*AccountLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountLoginRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 手机号码登录
type PhoneLoginRequest struct {
	Phone      string      `protobuf:"bytes,1,opt,name=Phone,json=phone" json:"Phone,omitempty"`
	Code       string      `protobuf:"bytes,2,opt,name=Code,json=code" json:"Code,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *PhoneLoginRequest) Reset()                    { *m = PhoneLoginRequest{} }
func (m *PhoneLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*PhoneLoginRequest) ProtoMessage()               {}
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PhoneLoginRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

type LoginReply struct {
	UUID     string `protobuf:"bytes,1,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	AutoCode string `protobuf:"bytes,2,opt,name=AutoCode,json=autoCode" json:"AutoCode,omitempty"`
	Token    string `protobuf:"bytes,3,opt,name=Token,json=token" json:"Token,omitempty"`
	Phone    string `protobuf:"bytes,4,opt,name=Phone,json=phone" json:"Phone,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 发送手机验证码
type AuthCodeRequest struct {
	Phone      string      `protobuf:"bytes,1,opt,name=Phone,json=phone" json:"Phone,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,2,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *AuthCodeRequest) Reset()                    { *m = AuthCodeRequest{} }
func (m *AuthCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthCodeRequest) ProtoMessage()               {}
func (*AuthCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthCodeRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

type Reply struct {
	Result bool `protobuf:"varint,1,opt,name=Result,json=result" json:"Result,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 自动登陆
type AutoLoginRequest struct {
	AutoCode   string      `protobuf:"bytes,1,opt,name=AutoCode,json=autoCode" json:"AutoCode,omitempty"`
	UUID       string      `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *AutoLoginRequest) Reset()                    { *m = AutoLoginRequest{} }
func (m *AutoLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*AutoLoginRequest) ProtoMessage()               {}
func (*AutoLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AutoLoginRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 账号绑定手机号码
type BindingPhoneRequest struct {
	Phone      string      `protobuf:"bytes,1,opt,name=Phone,json=phone" json:"Phone,omitempty"`
	UUID       string      `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	AuthCode   string      `protobuf:"bytes,3,opt,name=AuthCode,json=authCode" json:"AuthCode,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,4,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *BindingPhoneRequest) Reset()                    { *m = BindingPhoneRequest{} }
func (m *BindingPhoneRequest) String() string            { return proto.CompactTextString(m) }
func (*BindingPhoneRequest) ProtoMessage()               {}
func (*BindingPhoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BindingPhoneRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 绑定普通账号
type BindingAccountRequest struct {
	AutoCode   string      `protobuf:"bytes,1,opt,name=AutoCode,json=autoCode" json:"AutoCode,omitempty"`
	UserName   string      `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	PassWord   string      `protobuf:"bytes,3,opt,name=PassWord,json=passWord" json:"PassWord,omitempty"`
	UUID       string      `protobuf:"bytes,4,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,5,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *BindingAccountRequest) Reset()                    { *m = BindingAccountRequest{} }
func (m *BindingAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*BindingAccountRequest) ProtoMessage()               {}
func (*BindingAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BindingAccountRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 修改密码
type ChangePassWordRequest struct {
	PassWord   string      `protobuf:"bytes,1,opt,name=PassWord,json=passWord" json:"PassWord,omitempty"`
	UUID       string      `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,3,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *ChangePassWordRequest) Reset()                    { *m = ChangePassWordRequest{} }
func (m *ChangePassWordRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePassWordRequest) ProtoMessage()               {}
func (*ChangePassWordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ChangePassWordRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

// 微信登陆
type WeixinLoginRequest struct {
	Code       string      `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	DeviceInfo *DeviceInfo `protobuf:"bytes,2,opt,name=DeviceInfo,json=deviceInfo" json:"DeviceInfo,omitempty"`
}

func (m *WeixinLoginRequest) Reset()                    { *m = WeixinLoginRequest{} }
func (m *WeixinLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*WeixinLoginRequest) ProtoMessage()               {}
func (*WeixinLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *WeixinLoginRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceInfo)(nil), "SDKProto.DeviceInfo")
	proto.RegisterType((*RegisterRequest)(nil), "SDKProto.RegisterRequest")
	proto.RegisterType((*AccountLoginRequest)(nil), "SDKProto.AccountLoginRequest")
	proto.RegisterType((*PhoneLoginRequest)(nil), "SDKProto.PhoneLoginRequest")
	proto.RegisterType((*LoginReply)(nil), "SDKProto.LoginReply")
	proto.RegisterType((*AuthCodeRequest)(nil), "SDKProto.AuthCodeRequest")
	proto.RegisterType((*Reply)(nil), "SDKProto.Reply")
	proto.RegisterType((*AutoLoginRequest)(nil), "SDKProto.AutoLoginRequest")
	proto.RegisterType((*BindingPhoneRequest)(nil), "SDKProto.BindingPhoneRequest")
	proto.RegisterType((*BindingAccountRequest)(nil), "SDKProto.BindingAccountRequest")
	proto.RegisterType((*ChangePassWordRequest)(nil), "SDKProto.ChangePassWordRequest")
	proto.RegisterType((*WeixinLoginRequest)(nil), "SDKProto.WeixinLoginRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Login service

type LoginClient interface {
	Active(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*Reply, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginReply, error)
	LoginByAccount(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	LoginByPhone(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	AutoLogin(ctx context.Context, in *AutoLoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	ActhCode(ctx context.Context, in *AuthCodeRequest, opts ...grpc.CallOption) (*Reply, error)
	BindingPhone(ctx context.Context, in *BindingPhoneRequest, opts ...grpc.CallOption) (*LoginReply, error)
	ChangePassword(ctx context.Context, in *ChangePassWordRequest, opts ...grpc.CallOption) (*Reply, error)
	LoginByWeiXin(ctx context.Context, in *WeixinLoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Active(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/Active", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) LoginByAccount(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/LoginByAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) LoginByPhone(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/LoginByPhone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) AutoLogin(ctx context.Context, in *AutoLoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/AutoLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) ActhCode(ctx context.Context, in *AuthCodeRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/ActhCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) BindingPhone(ctx context.Context, in *BindingPhoneRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/BindingPhone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) ChangePassword(ctx context.Context, in *ChangePassWordRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/ChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) LoginByWeiXin(ctx context.Context, in *WeixinLoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/SDKProto.Login/LoginByWeiXin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Login service

type LoginServer interface {
	Active(context.Context, *DeviceInfo) (*Reply, error)
	Register(context.Context, *RegisterRequest) (*LoginReply, error)
	LoginByAccount(context.Context, *AccountLoginRequest) (*LoginReply, error)
	LoginByPhone(context.Context, *PhoneLoginRequest) (*LoginReply, error)
	AutoLogin(context.Context, *AutoLoginRequest) (*LoginReply, error)
	ActhCode(context.Context, *AuthCodeRequest) (*Reply, error)
	BindingPhone(context.Context, *BindingPhoneRequest) (*LoginReply, error)
	ChangePassword(context.Context, *ChangePassWordRequest) (*Reply, error)
	LoginByWeiXin(context.Context, *WeixinLoginRequest) (*LoginReply, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/Active",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Active(ctx, req.(*DeviceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_LoginByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/LoginByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginByAccount(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_LoginByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/LoginByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginByPhone(ctx, req.(*PhoneLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_AutoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).AutoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/AutoLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).AutoLogin(ctx, req.(*AutoLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_ActhCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).ActhCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/ActhCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).ActhCode(ctx, req.(*AuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_BindingPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).BindingPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/BindingPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).BindingPhone(ctx, req.(*BindingPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePassWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).ChangePassword(ctx, req.(*ChangePassWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_LoginByWeiXin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeixinLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginByWeiXin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SDKProto.Login/LoginByWeiXin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginByWeiXin(ctx, req.(*WeixinLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SDKProto.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Active",
			Handler:    _Login_Active_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Login_Register_Handler,
		},
		{
			MethodName: "LoginByAccount",
			Handler:    _Login_LoginByAccount_Handler,
		},
		{
			MethodName: "LoginByPhone",
			Handler:    _Login_LoginByPhone_Handler,
		},
		{
			MethodName: "AutoLogin",
			Handler:    _Login_AutoLogin_Handler,
		},
		{
			MethodName: "ActhCode",
			Handler:    _Login_ActhCode_Handler,
		},
		{
			MethodName: "BindingPhone",
			Handler:    _Login_BindingPhone_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Login_ChangePassword_Handler,
		},
		{
			MethodName: "LoginByWeiXin",
			Handler:    _Login_LoginByWeiXin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("LoginProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x56, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0xed, 0xd8, 0xae, 0x33, 0x7f, 0x69, 0xcb, 0xd2, 0x22, 0x37, 0x14, 0x8a, 0x7c, 0xe2,
	0x14, 0x89, 0x52, 0x55, 0x5c, 0x10, 0x4a, 0x93, 0xaa, 0x8a, 0x68, 0x21, 0x4a, 0x5b, 0x95, 0x0b,
	0x48, 0xc1, 0x59, 0x1c, 0xab, 0xc9, 0x6e, 0x88, 0xed, 0xd0, 0x1c, 0x10, 0x07, 0x9e, 0x80, 0x87,
	0xe1, 0x55, 0x78, 0x14, 0xce, 0xec, 0x6e, 0xd6, 0xf6, 0x26, 0xb1, 0x4b, 0x54, 0x0e, 0x5c, 0xac,
	0x9d, 0x99, 0xdd, 0x99, 0x6f, 0xbe, 0xfd, 0x66, 0x65, 0xd8, 0x38, 0xa1, 0x7e, 0x40, 0x5a, 0x23,
	0x1a, 0xd1, 0xea, 0x90, 0x7f, 0x91, 0x7d, 0xd6, 0x78, 0x25, 0x6c, 0xf7, 0x97, 0x06, 0xd0, 0xc0,
	0xe3, 0xc0, 0xc3, 0x4d, 0xf2, 0x91, 0xa2, 0xfb, 0x60, 0x1d, 0x77, 0x06, 0xb8, 0xd9, 0x70, 0xb4,
	0xc7, 0xda, 0x93, 0x72, 0xdb, 0xf2, 0x85, 0x85, 0x1c, 0x58, 0xa9, 0xf7, 0x3a, 0x84, 0xe0, 0xbe,
	0xa3, 0x8b, 0xc0, 0x8a, 0x37, 0x35, 0xd1, 0xa3, 0xe4, 0xfc, 0xf9, 0x64, 0x88, 0x9d, 0x92, 0x08,
	0x42, 0x37, 0xf5, 0x20, 0x04, 0x46, 0xf3, 0xf4, 0xa8, 0xe9, 0x18, 0x22, 0x62, 0x04, 0x6c, 0x8d,
	0x36, 0xa0, 0x74, 0x5a, 0xab, 0x3b, 0xa6, 0x70, 0x95, 0x06, 0xb5, 0xba, 0xd8, 0xd5, 0x1a, 0xef,
	0x3b, 0x96, 0xdc, 0xc5, 0xd6, 0xd2, 0x77, 0xe0, 0xac, 0xa4, 0xbe, 0x03, 0xb4, 0x06, 0xfa, 0x9b,
	0x33, 0xc7, 0x16, 0x1e, 0x9d, 0x9e, 0xa1, 0x0a, 0xd8, 0x27, 0x9d, 0x28, 0x88, 0xe2, 0x2e, 0x76,
	0xca, 0xc2, 0x6b, 0xf7, 0xa5, 0x8d, 0x76, 0xa0, 0x7c, 0x42, 0x89, 0x3f, 0x0d, 0x82, 0x08, 0x96,
	0xfb, 0x89, 0xc3, 0xfd, 0x0a, 0xeb, 0x6d, 0xec, 0x07, 0x61, 0x84, 0x47, 0x6d, 0xfc, 0x29, 0xc6,
	0x61, 0xc4, 0x93, 0x5d, 0x84, 0x78, 0xf4, 0x9a, 0xb5, 0x2c, 0xdb, 0xb7, 0x63, 0x69, 0xf3, 0x58,
	0xab, 0x13, 0x86, 0x97, 0x74, 0xd4, 0x95, 0x0c, 0xd8, 0x43, 0x69, 0xa3, 0x7d, 0x95, 0x42, 0x41,
	0xc1, 0xff, 0x7b, 0x9b, 0xd5, 0x84, 0xe2, 0x6a, 0x16, 0x4b, 0x88, 0xe1, 0x6b, 0xf7, 0x9b, 0x06,
	0xf7, 0x6a, 0x9e, 0x47, 0x63, 0x12, 0x89, 0xfb, 0xf9, 0x37, 0x28, 0x42, 0xb8, 0xdb, 0xea, 0x51,
	0x82, 0x67, 0x20, 0x6c, 0x82, 0x29, 0x9c, 0xb2, 0xbe, 0x39, 0xe4, 0x06, 0xbf, 0x8f, 0x3a, 0x65,
	0x54, 0x4e, 0x0b, 0x1b, 0x1e, 0x5b, 0xdf, 0xb2, 0x68, 0x0f, 0x40, 0xd6, 0x1b, 0xf6, 0x27, 0x3c,
	0xef, 0xc5, 0x45, 0xaa, 0x38, 0x23, 0x66, 0x6b, 0xde, 0x68, 0x2d, 0x8e, 0xa8, 0x52, 0xcf, 0xee,
	0x48, 0x9b, 0xa3, 0x3b, 0xa7, 0x57, 0x98, 0x48, 0xb1, 0x99, 0x11, 0x37, 0x32, 0xcc, 0x86, 0x82,
	0xd9, 0x7d, 0x07, 0xeb, 0x2c, 0x4f, 0x8f, 0x9f, 0xbb, 0xb9, 0xb9, 0xd9, 0x46, 0xf4, 0x25, 0x1b,
	0xd9, 0x05, 0x73, 0xda, 0x03, 0x9b, 0x9b, 0x36, 0x0e, 0xe3, 0x7e, 0x24, 0xb2, 0xda, 0x6d, 0x6b,
	0x24, 0x2c, 0xf7, 0x1a, 0x36, 0x78, 0x1f, 0xf3, 0x17, 0x9c, 0xf6, 0xa6, 0xcd, 0xf5, 0x96, 0x70,
	0xa1, 0x2b, 0x5c, 0xdc, 0x8e, 0xe3, 0xef, 0x4c, 0x5e, 0x87, 0x01, 0xe9, 0x06, 0xc4, 0x17, 0xed,
	0xfe, 0xf1, 0x6e, 0x17, 0xea, 0x4e, 0x71, 0x0a, 0xee, 0x24, 0xd5, 0x1c, 0xa7, 0xb0, 0xe7, 0x30,
	0x19, 0x4b, 0x62, 0xfa, 0xa1, 0xc1, 0x96, 0xc4, 0x24, 0x95, 0xbf, 0x0c, 0x27, 0xea, 0x40, 0xe8,
	0x37, 0x0c, 0x44, 0x69, 0x6e, 0x20, 0x92, 0x9e, 0x8c, 0x42, 0x2e, 0xcd, 0x25, 0x71, 0x7f, 0x81,
	0x2d, 0xfe, 0xfa, 0xf9, 0x38, 0xa9, 0xa5, 0xc0, 0x4e, 0xcb, 0x6b, 0x05, 0xe5, 0xff, 0xfe, 0x2a,
	0xdf, 0x03, 0xba, 0xc4, 0xc1, 0x75, 0x40, 0x66, 0x64, 0xc4, 0xf2, 0x7b, 0x19, 0x5d, 0x79, 0xe3,
	0xb8, 0xa4, 0x8a, 0xf7, 0x7e, 0x1a, 0x60, 0x8a, 0xd4, 0xe8, 0x29, 0x58, 0x35, 0x2f, 0x0a, 0xc6,
	0x6c, 0xc8, 0xf2, 0x4e, 0x55, 0xd6, 0x33, 0xaf, 0xd0, 0xbd, 0xfb, 0x1f, 0x7a, 0x01, 0x76, 0xf2,
	0x8e, 0xa2, 0x6d, 0x35, 0x3c, 0xf3, 0xb6, 0x56, 0x94, 0x7c, 0xd9, 0xe8, 0xb3, 0xe3, 0xc7, 0xb0,
	0x26, 0xec, 0xc3, 0x89, 0x54, 0x04, 0x7a, 0x98, 0xed, 0xcc, 0x79, 0x1e, 0x0b, 0x13, 0xd5, 0x61,
	0x55, 0x26, 0x12, 0xf2, 0x46, 0x0f, 0xb2, 0x7d, 0x0b, 0x0f, 0x5c, 0x61, 0x92, 0x97, 0x50, 0x4e,
	0xc7, 0x15, 0x55, 0x14, 0x20, 0x73, 0x33, 0x5c, 0x98, 0xe0, 0x39, 0xd3, 0xb1, 0x27, 0x67, 0x64,
	0x7b, 0xe6, 0xbc, 0xfa, 0x06, 0xe5, 0xf1, 0x78, 0x04, 0xab, 0xea, 0xb8, 0xaa, 0x34, 0xe4, 0x8c,
	0x71, 0x21, 0x80, 0x06, 0xac, 0x65, 0x52, 0xfd, 0xcc, 0x75, 0xb8, 0x9b, 0xed, 0xcc, 0x15, 0x71,
	0x3e, 0x98, 0x3b, 0x92, 0x4c, 0x26, 0xbc, 0xb7, 0x8c, 0x8b, 0x9d, 0x6c, 0xcf, 0xa2, 0x14, 0x8b,
	0xc0, 0x1c, 0xae, 0x02, 0x78, 0x74, 0x50, 0x25, 0x57, 0xfc, 0x2f, 0xe2, 0x83, 0x25, 0xfe, 0x3d,
	0x9e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x41, 0xee, 0xc6, 0x47, 0x8f, 0x08, 0x00, 0x00,
}
